### ISSUE TITLE
Reliability of sending/receiving messages

### ISSUE THREAD

**Issue by dajeong265** [regulusweb/ucsc-tz-labor#33] opened 2018-07-09 18:10 UTC
This maybe a little difficult to explain why it's happening, but this happened to me today twice while testing. Some messages that were recorded to be sent from Telerivet do not reach my cell phone inbox.

I initiated the random farmer survey by typing Utafiti ("survey"). 

**Example 1.** 
You can see that one question is skipped between 20:20 and 20:27, even if it is shown in the Telerivet. 

<img width="766" alt="screen shot 2018-07-09 at 8 27 34 pm" src="https://user-images.githubusercontent.com/24502003/42467168-d13b6c46-83b9-11e8-84d3-44ab1e3aeeb7.png">

![whatsapp image 2018-07-09 at 20 28 54](https://user-images.githubusercontent.com/24502003/42467423-89ce25fa-83ba-11e8-8cb2-ea91f5493cd9.jpeg)

**Example 2.** 
This is another example. One question is skipped between 20:50 and 21:02.
<img width="768" alt="screen shot 2018-07-09 at 9 08 04 pm" src="https://user-images.githubusercontent.com/24502003/42468029-4e963598-83bc-11e8-8b53-2798e1259f0b.png">
![whatsapp image 2018-07-09 at 21 04 23](https://user-images.githubusercontent.com/24502003/42468031-4f53eda4-83bc-11e8-9f1c-f79e13c1bde5.jpeg)

**Comment by dajeong265** [comment] 2018-07-09 18:35
This issue is not restricted to the random farmer surveys only.

I faced this issue while I am testing `start` and `stop` keywords as well. The message is sent from the Telerivet, but the phone does not receive it.

**Comment by craigloftus** [comment] 2018-07-09 19:22
This is most likely an issue with your phones connection. When connected to a real wifi network it will be a lot more reliable.

**Comment by dajeong265** [comment] 2018-07-09 19:50
You mean the connection of the router phone, or the phones I am testing this with?

The router phone is now sitting in my office with wifi + mobile data 24 hours. 

So I guess, the problem is the phones I am testing this with. In other words, if farmers are using phones in remote areas with unreliable mobile network connection, then this could happen as well?

**Comment by craigloftus** [comment] 2018-07-10 14:20
Yeah, I was referring to the router phone.

I've been trying to look into this, and I can't see any issue with how we are using telerivet, and as you saw the messages are all appearing the telerivet logs.

It would be worth checking that the messages are appearing the sent log of your phone. If they're not that would suggest an issue with the telerivet system that we should raise a support ticket for.

It is possible it is just the mobile network, sms is not the most reliable communication system, and as i believe we discussed early on we see a lot of problems with delivery in Kenya.

**Comment by dajeong265** [comment] 2018-07-11 13:15
Ok. I don't know why, but recently it has become quite unreliable. In a given attempt of job posting, at least 1-2 messages are taking 5-8 minutes.

I think it could be that I am in remote areas now (but the Router Phone is in the main city in my office). But this could be a relevant setting, because many farmers live in remote areas. I'll try to test these again when I am back to city tomorrow.  

But unfortunately, I'd like more rigorous testing before I sign off. If there is any urgent need of cash on your company side, I can imagine letting you guys invoice for now. But otherwise, I would need more time reviewing it.

**Comment by dajeong265** [comment] 2018-07-11 14:55
I might be experiencing the problems that we faced in the first week of development, i.e., some logics are in a mixed order in my cell phone, while it is in the right order in the Telerivet. 

I don't think this is an anomaly, at least in an environment I am in, because it has been happening in all tests I've done for the past few hours.

**Comment by craigloftus** [comment] 2018-07-11 20:06
When you're back in the city please check the message history in the sms app to see if the skipped messages appear there. That will tell us a lot about where the problem is and if anything can be done about it.

**Comment by dajeong265** [comment] 2018-07-12 18:39
I am back in the city, and checked the router phone, and every message is in the right order. 

What happened was that the router phone did always reply immediately, but there were two kinds of problems in the farmer phone I was testing with.
(1) the message sent by the router phone was never received in my farmer phone, or
(2) the message sent by the router phone was delivered 2-3 hours later

From what you said, since the router phone did send correctly, it has nothing to do with the Telerivet, but it was probably the mobile network of my farmer phone that failed to receive the message that had been sent by the router phone. 

Is my interpretation correct? 

I am not suggesting this right now under the current project budget, but can you think of ways to make this more reliable? Like the double check marks in WhatsApp, is there a way for the Telerivet or the router phone to capture whether the message was successfully received by the receiving phone? I think in the above examples I described, the problem was not the sending phone, but the receiving phone, which could happen in a real setting.

**Comment by craigloftus** [comment] 2018-07-13 08:45
Yeah, you're interpretation is correct.

I think it is a tricky problem, and yeah, it is probably worth talking it through with telerivet.

I'm going to close this for now, as it isn't something I can address.

**Closed by craigloftus** 2018-07-13 08:45 UTC
